### ISSUE TITLE
postJson should accept request headers

### ISSUE THREAD

**Issue by moodmosaic** [chrisdone/dynamic#3]
In addition to the `User-Agent` one, it'd be nice if one could specify additional request headers.
https://github.com/chrisdone/dynamic/blob/e90b1d8fc8599b33ee355d42215cf06c7f59b077/src/Dynamic.hs#L415-L426

**Comment by chrisdone** [comment]
I wanted this too. Added it!

**Comment by moodmosaic** [comment]
🎉
